export interface InterviewQuestion {
  id: string;
  category: "behavioral" | "technical" | "situational" | "role-specific";
  question: string;
  tips: string[];
  sampleAnswer?: string;
  roleType?: string[];
}

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  {
    id: "Tell me about yourself",
    category: "behavioral",
    question: "Tell me about yourself",
    tips: [
      "Keep it under 2 minutes",
      "Start with your current role and recent experience",
      "Connect your past experience to this role",
      "End with why you're interested in this position",
    ],
    sampleAnswer: "I'm a software developer with 3 years of experience building web applications. Currently, I work at a fintech startup where I lead frontend development using React and TypeScript. Before that, I studied Computer Science at KNUST. I'm excited about this role because...",
    roleType: ["all"],
  },
  {
    id: "strengths-weaknesses",
    category: "behavioral",
    question: "What are your greatest strengths and weaknesses?",
    tips: [
      "Choose strengths relevant to the job",
      "For weakness, pick something real but not critical",
      "Explain what you're doing to improve",
      "Be specific with examples",
    ],
    sampleAnswer: "My greatest strength is my problem-solving ability. In my last role, I debugged a critical payment issue that had stumped the team for days. For weaknesses, I've been working on public speaking - I've started leading more team meetings to practice.",
    roleType: ["all"],
  },
  {
    id: "why-this-company",
    category: "behavioral",
    question: "Why do you want to work at this company?",
    tips: [
      "Research the company beforehand",
      "Mention specific products, values, or missions",
      "Connect your goals to what the company does",
      "Avoid generic answers like 'great company'",
    ],
    roleType: ["all"],
  },
  {
    id: "team-conflict",
    category: "behavioral",
    question: "Describe a time you had a conflict with a coworker",
    tips: [
      "Choose a professional conflict (not personal)",
      "Focus on resolution, not the conflict itself",
      "Show emotional intelligence",
      "Use the STAR method",
    ],
    sampleAnswer: "During a project, a colleague and I disagreed on the technical approach. I scheduled a one-on-one to understand their perspective. We realized both approaches had merit, so we combined elements and delivered a better solution than either would have alone.",
    roleType: ["all"],
  },
  {
    id: "leadership-example",
    category: "behavioral",
    question: "Tell me about a time you demonstrated leadership",
    tips: [
      "You don't need a formal leadership role",
      "Focus on initiative and influence",
      "Describe the outcome and impact",
      "Show what you learned",
    ],
    roleType: ["all"],
  },
  {
    id: "failure-lesson",
    category: "behavioral",
    question: "Tell me about a time you failed and what you learned",
    tips: [
      "Choose a real but recoverable failure",
      "Take responsibility",
      "Focus on lessons learned",
      "Show growth mindset",
    ],
    sampleAnswer: "I missed a project deadline because I underestimated the complexity. I communicated early with stakeholders and worked overtime to deliver quality work. Now I always add buffer time and break large tasks into smaller milestones.",
    roleType: ["all"],
  },
  {
    id: "problem-solving",
    category: "behavioral",
    question: "Describe a challenging problem and how you solved it",
    tips: [
      "Choose a relevant technical or business problem",
      "Show your thinking process",
      "Quantify the results if possible",
      "Be specific about your contribution",
    ],
    roleType: ["all"],
  },
  {
    id: "pressure-handling",
    category: "situational",
    question: "How do you handle working under pressure?",
    tips: [
      "Acknowledge that pressure is part of work",
      "Share specific strategies",
      "Give an example",
      "Show you're calm under stress",
    ],
    sampleAnswer: "I prioritize tasks by urgency and impact. When facing tight deadlines, I break work into smaller chunks and communicate proactively with stakeholders. For example, during a product launch, I created a daily tracker that helped the team stay aligned and we delivered on time.",
    roleType: ["all"],
  },
  {
    id: "multitasking",
    category: "situational",
    question: "How do you handle multiple projects at once?",
    tips: [
      "Show organization skills",
      "Mention tools you use",
      "Be honest about limits",
      "Emphasize communication",
    ],
    roleType: ["all"],
  },
  {
    id: "career-goals",
    category: "situational",
    question: "Where do you see yourself in 5 years?",
    tips: [
      "Be realistic but ambitious",
      "Align with the company's growth",
      "Show you plan to stay",
      "Focus on skills and impact",
    ],
    roleType: ["all"],
  },
  {
    id: "adaptation",
    category: "situational",
    question: "How do you adapt to change?",
    tips: [
      "Show flexibility and learning ability",
      "Give an example of adapting to change",
      "Emphasize continuous learning",
    ],
    roleType: ["all"],
  },
  {
    id: "tech-stack",
    category: "technical",
    question: "What technologies are you most proficient in?",
    tips: [
      "Be honest about your level",
      "Give practical examples of use",
      "Mention you're learning",
      "Connect to the job requirements",
    ],
    roleType: ["developer", "engineer", "data"],
  },
  {
    id: "code-review",
    category: "technical",
    question: "Describe your code review process",
    tips: [
      "Show attention to detail",
      "Mention both giving and receiving feedback",
      "Focus on code quality and best practices",
      "Be open to learning",
    ],
    roleType: ["developer", "engineer"],
  },
  {
    id: "system-design",
    category: "technical",
    question: "How would you design a scalable system?",
    tips: [
      "Start with understanding requirements",
      "Discuss components and their interactions",
      "Consider scaling, reliability, maintainability",
      "Think out loud",
    ],
    sampleAnswer: "First, I'd clarify requirements - what's the scale, read/write ratio, latency needs? Then I'd design the API layer, database choice, caching strategy, and consider horizontal scaling. I'd also discuss monitoring, error handling, and trade-offs.",
    roleType: ["developer", "engineer", "architect"],
  },
  {
    id: "debugging",
    category: "technical",
    question: "How do you approach debugging a complex issue?",
    tips: [
      "Show systematic thinking",
      "Mention specific tools",
      "Emphasize understanding root cause",
      "Show patience and persistence",
    ],
    roleType: ["developer", "engineer", "data"],
  },
  {
    id: "data-analysis",
    category: "technical",
    question: "How do you approach analyzing a new dataset?",
    tips: [
      "Start with understanding the data",
      "Check for missing values and outliers",
      "Form hypotheses before diving in",
      "Visualize to find patterns",
    ],
    roleType: ["data", "analyst", "scientist"],
  },
  {
    id: "sql-basics",
    category: "technical",
    question: "Write a SQL query to find duplicate records",
    tips: [
      "Use GROUP BY and HAVING",
      "Show understanding of aggregation",
      "Consider multiple approaches",
      "Explain your thought process",
    ],
    sampleAnswer: "SELECT email, COUNT(*) as cnt FROM users GROUP BY email HAVING COUNT(*) > 1",
    roleType: ["data", "developer", "analyst"],
  },
  {
    id: "frontend-framework",
    category: "technical",
    question: "What are the pros and cons of React vs Vue?",
    tips: [
      "Show you understand both",
      "Be balanced in your analysis",
      "Know when to use each",
      "Mention current industry trends",
    ],
    roleType: ["frontend", "developer"],
  },
  {
    id: "salary-expectation",
    category: "situational",
    question: "What are your salary expectations?",
    tips: [
      "Research market rates for the role",
      "Give a range instead of exact number",
      "Consider total compensation",
      "Be flexible but know your worth",
    ],
    roleType: ["all"],
  },
  {
    id: "questions-for-us",
    category: "situational",
    question: "Do you have any questions for us?",
    tips: [
      "Always say yes",
      "Ask about team, culture, growth",
      "Avoid salary in first interview",
      "Show genuine interest",
    ],
    sampleAnswer: "I have a few questions: What does success look like in this role after 6 months? What's the team structure and how do you collaborate? What opportunities are there for learning and growth?",
    roleType: ["all"],
  },
];

export const QUESTION_CATEGORIES = [
  { id: "all", label: "All Questions", icon: "📋" },
  { id: "behavioral", label: "Behavioral", icon: "💬" },
  { id: "technical", label: "Technical", icon: "💻" },
  { id: "situational", label: "Situational", icon: "🎯" },
  { id: "role-specific", label: "Role-Specific", icon: "🎯" },
] as const;

export const ROLE_TYPES = [
  { id: "all", label: "All Roles" },
  { id: "developer", label: "Developer" },
  { id: "engineer", label: "Engineer" },
  { id: "data", label: "Data/Analytics" },
  { id: "analyst", label: "Analyst" },
  { id: "frontend", label: "Frontend" },
  { id: "scientist", label: "Scientist" },
  { id: "architect", label: "Architect" },
  { id: "marketing", label: "Marketing" },
  { id: "sales", label: "Sales" },
  { id: "design", label: "Design" },
  { id: "hr", label: "HR" },
  { id: "manager", label: "Manager" },
] as const;

export const ROLE_SPECIFIC_QUESTIONS: InterviewQuestion[] = [
  {
    id: "portfolio-walkthrough",
    category: "role-specific",
    question: "Walk me through your portfolio or recent project",
    tips: [
      "Choose your best 2-3 projects",
      "Explain your role and contributions",
      "Highlight challenges and solutions",
      "Show measurable results",
    ],
    sampleAnswer: "My most impactful project was building an e-commerce checkout that reduced cart abandonment by 25%. I led the frontend development using React, worked closely with UX on the flow, and collaborated with backend on API integration. The key challenge was optimizing for slow networks...",
    roleType: ["developer", "frontend", "design"],
  },
  {
    id: "design-process",
    category: "role-specific",
    question: "Describe your design process from concept to delivery",
    tips: [
      "Show you follow a structured approach",
      "Include user research and testing",
      "Mention collaboration with stakeholders",
      "Discuss iteration based on feedback",
    ],
    roleType: ["design", "frontend"],
  },
  {
    id: "campaign-strategy",
    category: "role-specific",
    question: "How would you develop a marketing campaign?",
    tips: [
      "Start with understanding goals and audience",
      "Mention channels based on target market",
      "Include measurement and KPIs",
      "Show knowledge of African markets",
    ],
    sampleAnswer: "First, I'd define clear objectives - awareness, leads, or conversions. Then research the target audience, their pain points, and preferred channels. I'd create content that resonates culturally, choose channels like social media and WhatsApp, and set up tracking to measure ROI.",
    roleType: ["marketing", "manager"],
  },
  {
    id: "market-research",
    category: "role-specific",
    question: "How do you conduct market research?",
    tips: [
      "Mention both primary and secondary research",
      "Discuss competitor analysis",
      "Include customer surveys and interviews",
      "Show how you use data to inform decisions",
    ],
    roleType: ["marketing", "analyst", "manager"],
  },
  {
    id: "sales-approach",
    category: "role-specific",
    question: "Describe your approach to closing a sale",
    tips: [
      "Focus on understanding customer needs",
      "Build rapport and trust",
      "Address objections effectively",
      "Know when to walk away",
    ],
    roleType: ["sales"],
  },
  {
    id: "pipeline-management",
    category: "role-specific",
    question: "How do you manage your sales pipeline?",
    tips: [
      "Show organization and tracking skills",
      "Mention CRM tools you use",
      "Discuss prioritization",
      "Include forecasting approach",
    ],
    roleType: ["sales", "manager"],
  },
  {
    id: "recruitment-process",
    category: "role-specific",
    question: "How would you source candidates for a hard-to-fill role?",
    tips: [
      "Mention multiple sourcing channels",
      "Discuss employer branding",
      "Include employee referrals",
      "Show understanding of candidate experience",
    ],
    roleType: ["hr", "manager"],
  },
  {
    id: "employee-retention",
    category: "role-specific",
    question: "How do you approach employee retention?",
    tips: [
      "Show understanding of motivation factors",
      "Mention career development",
      "Discuss compensation and benefits",
      "Include culture and work-life balance",
    ],
    roleType: ["hr", "manager"],
  },
  {
    id: "budget-management",
    category: "role-specific",
    question: "How do you manage a team budget?",
    tips: [
      "Show financial planning skills",
      "Discuss prioritization of spend",
      "Mention tracking and reporting",
      "Include cost-saving initiatives",
    ],
    roleType: ["manager", "hr", "marketing"],
  },
  {
    id: "stakeholder-management",
    category: "role-specific",
    question: "How do you manage stakeholders with conflicting priorities?",
    tips: [
      "Show communication and negotiation skills",
      "Mention data-driven decision making",
      "Discuss setting clear expectations",
      "Include escalation when needed",
    ],
    sampleAnswer: "I first seek to understand each stakeholder's perspective and underlying concerns. Then I facilitate a discussion to align on shared goals. When conflicts arise, I use data to support decisions and ensure transparency. If needed, I escalate to leadership with clear recommendations.",
    roleType: ["manager"],
  },
  {
    id: "team-conflict-resolution",
    category: "role-specific",
    question: "How do you handle conflict within your team?",
    tips: [
      "Address issues early",
      "Listen to all parties",
      "Focus on facts, not personalities",
      "Find common ground and solutions",
    ],
    roleType: ["manager", "hr"],
  },
  {
    id: "performance-management",
    category: "role-specific",
    question: "How do you approach performance reviews?",
    tips: [
      "Be fair and consistent",
      "Give specific, actionable feedback",
      "Set clear goals together",
      "Follow up regularly, not just annually",
    ],
    roleType: ["manager", "hr"],
  },
  {
    id: "ml-model-selection",
    category: "role-specific",
    question: "How do you choose the right ML model for a problem?",
    tips: [
      "Start with understanding the problem type",
      "Consider data availability and quality",
      "Discuss trade-offs between accuracy and interpretability",
      "Mention testing and validation approach",
    ],
    roleType: ["data", "scientist"],
  },
  {
    id: "data-visualization",
    category: "role-specific",
    question: "How do you approach creating a data visualization?",
    tips: [
      "Know your audience and their needs",
      "Choose the right chart type",
      "Keep it simple and focused",
      "Tell a story with the data",
    ],
    sampleAnswer: "First, I identify what question the visualization should answer and who will view it. Then I choose the appropriate chart type - bar for comparisons, line for trends, pie for proportions. I keep design clean, use color purposefully, and include clear labels and annotations.",
    roleType: ["data", "analyst", "design"],
  },
  {
    id: "agile-scrum",
    category: "role-specific",
    question: "Explain your experience with Agile/Scrum",
    tips: [
      "Show understanding of sprint cycles",
      "Discuss stand-ups, retrospectives",
      "Mention estimation techniques",
      "Include handling scope changes",
    ],
    roleType: ["developer", "engineer", "manager"],
  },
  {
    id: "api-design",
    category: "role-specific",
    question: "How do you design a RESTful API?",
    tips: [
      "Use proper HTTP methods and status codes",
      "Design intuitive endpoints",
      "Consider versioning and documentation",
      "Handle errors gracefully",
    ],
    sampleAnswer: "I start with resource modeling - identifying what entities the API manages. Then I design intuitive endpoints using nouns, not verbs. I ensure proper use of HTTP methods, consistent error responses, and include pagination for lists. Documentation with examples is essential.",
    roleType: ["developer", "engineer"],
  },
  {
    id: "cybersecurity-incident",
    category: "role-specific",
    question: "How would you respond to a security breach?",
    tips: [
      "Show incident response process",
      "Mention containment, investigation, recovery",
      "Discuss communication with stakeholders",
      "Include prevention measures after",
    ],
    roleType: ["developer", "engineer"],
  },
  {
    id: "remote-collaboration",
    category: "role-specific",
    question: "How do you stay productive while working remotely?",
    tips: [
      "Show self-discipline and organization",
      "Mention communication tools",
      "Discuss setting boundaries",
      "Include maintaining work-life balance",
    ],
    roleType: ["all"],
  },
  {
    id: "growing-market",
    category: "role-specific",
    question: "How do you approach selling in emerging African markets?",
    tips: [
      "Show cultural awareness",
      "Discuss mobile-first approach",
      "Mention local payment methods",
      "Include building trust and relationships",
    ],
    roleType: ["sales", "marketing", "manager"],
  },
  {
    id: "tech-in-africa",
    category: "role-specific",
    question: "What opportunities do you see in Africa's tech ecosystem?",
    tips: [
      "Show you follow African tech trends",
      "Mention specific sectors like fintech, agritech",
      "Discuss challenges like infrastructure",
      "Highlight the entrepreneurial spirit",
    ],
    sampleAnswer: "Africa has enormous potential with a young, mobile-first population. I'm excited about fintech reaching the unbanked, agritech improving food security, and edtech making learning accessible. The challenges are real - infrastructure, regulation - but that's what makes it an exciting space to build.",
    roleType: ["all"],
  },
];
